dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.0

compiler:
  minify_source: false
  solc:
    version: 0.8.15
    optimizer:
            enabled: true
            runs: 1
    remappings:
            - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.7.0/contracts"
